### ISSUE TITLE
模型训练过程中如何更好的保留人声

### ISSUE THREAD

**Issue by hulucky1102** [ioyy900205/MFNet#5]
您好，大佬有个问题想请教下，训练模型的过程中如何更好的保留人声（目前主要为远场5m左右的距离，信噪比较低，主要场景为稳态噪声中存在部分瞬态噪声），训练损失使用多分辨率具有压缩的幅度和复数的mse（噪声抑制强度高）,使用了非对称函数和sisnr来提高人声的保留，但这样存在噪声残留较多且波动较大，听感上不好。{隔了半年又来请教问题了，和论文没啥相关性哈，若能回复不甚感激}

**Comment by ioyy900205** [comment]
这是个大家都很关注的问题。我只能说一下我自己的理解和认同的地方：
1. **使用压缩谱**：在处理远场语音信号时，压缩谱确实是一种有效的方法。它可以帮助减少噪声的影响，同时保留人声的重要特征。通过压缩谱，可以降低噪声的能量，使得人声信号更加突出。此外，压缩谱还可以改善信号的动态范围，使得模型更容易学习到人声的特征。

2.**非对称函数**：我猜测是通过使用 RELU(pred_wav - clean_wav)，模型可以更好地关注到预测误差较大的部分，从而提高人声的清晰度。

3. **多目标优化**：在训练过程中，确实需要考虑多个目标的优化。单一的损失函数可能无法同时满足噪声抑制和人声保留的需求。通过调整这些损失项的权重，可以在噪声抑制和人声保留之间找到一个平衡点。

4. **突出人声的策略**：
**VAD（Voice Activity Detection）信息**：利用VAD信息可以帮助模型识别出语音活跃的区域，从而在这些区域中更加注重人声的保留。通过这种方式，模型可以避免在非语音区域过度增强噪声。
**语谱连续性**：人声信号具有自然的连续性和周期性。在训练过程中，可以通过优化语谱的连续性来提高人声的自然度。例如，可以使用一些正则化项来鼓励模型生成连续平滑的语谱。
**潜变量距离**：通过计算人声和噪声的潜变量距离，可以使用对比损失来指导模型更好地区分人声和噪声。这种方法可以帮助模型学习到更深层次的人声特征，从而在噪声环境中更好地保留人声。

**Comment by hulucky1102** [comment]
感谢大佬回复:
1. 目前VAD也有在做，主要是实时VAD存在人声起来具有滞后性（会起来的慢一点点），而且对于低信噪比场景用目前开源silero-vad会起不来（我觉得可能会导致误判，人声丢失更加严重）.
2. 目前模型降噪后是能保留人声的，我压缩谱的因子设置的为0.3，这边的实验结果是仅使用压缩谱低信噪比人声成分丢失较为严重.
3. 非对称函数我这边是relu（clean_wav-pre_wav）,我个人理解是当clean>pre时证明语音被过度抑制了。希望大佬指正
4. 潜变量距离能略微详细说说么（若有相关论文发我一下就更好了）。

**Comment by hulucky1102** [comment]
感谢大佬回复:

1. 目前VAD也有在做，主要是实时VAD存在人声起来具有滞后性（会起来的慢一点点），而且对于低信噪比场景用目前开源silero-vad会起不来（我觉得可能会导致误判，人声丢失更加严重），而目前模型对该人声降噪后是能保留的。
2. 我压缩谱的因子设置的为0.3，这边的实验结果是仅使用压缩谱低信噪比人声成分丢失较为严重.
3. 非对称函数我这边是relu（clean_wav-pre_wav）,我个人理解是当clean>pre时证明语音被过度抑制了。希望大佬指正
4. 潜变量距离能略微详细说说么（若有相关论文发我一下就更好了）。

**Comment by ioyy900205** [comment]
额。
1. 我理解你的思路是在当前已有降噪模型的基础上叠VAD模型，进一步处理。我的意思是，直接对着clean_wav做vad，可获得vad标签。那么在做loss的时候，对活动人声部分进行加强。理解上就是，在voice active部分使用更加困难的loss。因为在voice nonactive部分是非常容易学习的，如果使用同一个loss对整体语音优化，会导致非语音段优化良好，但是人声段略差。

2. 低信噪比情况下，确实是需要单独讨论。

3. 认可你的理解。我的表述有误。:）

4. 参考：https://arxiv.org/abs/2305.10761 。

**Comment by hulucky1102** [comment]
感谢感谢，我去研究研究。

**Comment by hulucky1102** [comment]
抱歉再次打扰，关于您推荐给我的论文《NOISE-AWARE SPEECH SEPARATION WITH CONTRASTIVE LEARNING》，有个疑问想请教下。其中Patch-wise Contrasive Learning是否只在训练过程中存在，在前向推理过程中其实是不使用的。

**Comment by ioyy900205** [comment]
是的。对比学习嘛。我之前的实验也发现了对比学习的有效性，只不过是在音视频分离任务上。你还可以参考这一篇：
CURRICULAR CONTRASTIVE REGULARIZATION FOR SPEECH ENHANCEMENT WITH
SELF-SUPERVISED REPRESENTATIONS
感觉都是无痛提升技术。

**Comment by hulucky1102** [comment]
该论文《NOISE-AWARE SPEECH SEPARATION WITH CONTRASTIVE LEARNING》可能在语音增强中效果不佳（个人实验），形状[F, L] 卷积后变为[F-H+1, L-H+1]，对于长度4s的训练音频，特征数为257的数据，仅取256个点进行对比，并且其训练batchsize为1，让我感到困惑，过来请教一番。

**Comment by ioyy900205** [comment]
1. **取 256个点**。第0个点是直流分量可去掉，单纯的语音增强也可以这么干，直接把第一个点丢掉。恢复的时候补0即可。
2. **batchsize = 1**。 我仅猜测，batchsize 大于1的时候，单个s1 和 s2的信息会由bn泄露，之前simsiam、BYOL这种对比学习都有争论过bn的问题。我其实也不理解，只能根据过去的经验判断。
![image](https://github.com/ioyy900205/MFNet/assets/76168691/a885bfcd-da5d-4284-a50b-656f5ba6ea08)
3.形状[F, L] 卷积后变为[F-H+1, **L-H+1]**。我不理解要表达什么

**Comment by hulucky1102** [comment]
我想表达的意思是，对于窗长512窗移256，长度4s，16k采样的音频数据求出的特征为[257,251]，Patch-wise Contrasive Learing中定义
![image](https://github.com/ioyy900205/MFNet/assets/56753631/3a666221-ece2-4f1a-80f0-c2a4f6f8cff6)
其实是论文中没有表述清楚，这个就是用特征图过来两个核为3*3的卷积，然后特征变成了[253,247],在该特征中只取了256个点给后续对比计算使用。
